apiVersion: v1
kind: Namespace
metadata:
    name: $org

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: $pvName
  labels:
    org: $org
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  nfs:
    path: $path
    server: 10.88.68.51  #change to your nfs server ip here

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 namespace: $org
 name: $pvName
spec:
 accessModes:
   - ReadWriteMany
 resources:
   requests:
     storage: 10Mi
 selector:
   matchLabels:
     org: $org   

---