apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cli
  namespace: $namespace
spec:
  replicas: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cli
    spec:
      containers:
      - args:
        - /bin/bash
        env:
        - name: CORE_PEER_ADDRESS
          value: $peerID.$namespace:7051
        - name: CORE_PEER_ID
          value: cli
        - name: CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE
          value: bridge
        - name: CORE_PEER_LOCALMSPID
          value: $localMSPID
        - name: CORE_PEER_MSPCONFIGPATH
          value: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/$namespace/users/Admin@$namespace/msp
        - name: CORE_PEER_TLS_CERT_FILE
          value: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/$namespace/peers/$peerID.$namespace/tls/server.crt
        - name: CORE_PEER_TLS_ENABLED
          value: "true"
        - name: CORE_PEER_TLS_KEY_FILE
          value: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/$namespace/peers/$peerID.$namespace/tls/server.key
        - name: CORE_PEER_TLS_ROOTCERT_FILE
          value: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/$namespace/peers/$peerID.$namespace/tls/ca.crt
        - name: CORE_VM_ENDPOINT
          value: unix:///host/var/run/docker.sock
        - name: FABRIC_LOGGING_SPEC
          value: INFO
        - name: GOPATH
          value: /opt/gopath
        - name: SYS_CHANNEL
          value: byfn-sys-channel
        image: hyperledger/fabric-tools:latest
        name: cli
        resources: {}
        stdin: true
        tty: true
        volumeMounts:
        - mountPath: /host/var/run/
          name: cli-claim0
        - mountPath: /opt/gopath/src/github.com/chaincode
          name: cli-claim1
        - mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
          name: cli-claim2
        - mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
          name: cli-claim3
        - mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
          name: cli-claim4
        workingDir: /opt/gopath/src/github.com/hyperledger/fabric/peer
      restartPolicy: Always
      volumes:
      - name: cli-claim0
        hostPath:
          path: /var/run/ 
          type: Directory
      - name: cli-claim1
        hostPath:
          path: $baseDir/chaincode
          type: Directory
      - name: cli-claim2
        hostPath:
          path: $baseDir/crypto-config 
          type: Directory
      - name: cli-claim3
        hostPath:
          path: $baseDir/scripts 
          type: Directory
      - name: cli-claim4
        hostPath:
          path: $baseDir/channel-artifacts 
          type: Directory
status: {}
