apiVersion: v1
kind: Namespace
metadata:
    name: org2

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: org2
  name:	peer1-org2
  
spec:
  replicas: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
       app: hyperledger
       role: peer
       peer-id: peer1
       org: org2
    spec:
      containers:
      - name: couchdb-peer1
        image: hyperledger/fabric-couchdb:x86_64-1.0.0
        ports:
          - containerPort: 5984
  
      - name: peer1-org2
        image: hyperledger/fabric-peer:latest
        ports:
         - containerPort: 7051
         - containerPort: 7052
         - containerPort: 7053		
        command: ["peer"]
        args: ["node","start"]
        env:
        - name: CORE_LEDGER_STATE_STATEDATABASE
          value: "CouchDB"
        - name: CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS
          value: "localhost:5984"
        - name: CORE_PEER_ADDRESS
          value: peer1.org2:7051
        - name: CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE 
          value: bridge 
        - name: CORE_PEER_ADDRESSAUTODETECT
          value: "true"		
#        - name: CORE_PEER_CHAINCODEADDRESS
#          value: peer1.org2:7052
#        - name: CORE_PEER_CHAINCODELISTENADDRESS
#          value: 0.0.0.0:7052
        - name: CORE_PEER_GOSSIP_BOOTSTRAP
          value: 0.0.0.0:7051
        - name: CORE_PEER_GOSSIP_EXTERNALENDPOINT
          value: peer1.org2:7051
        - name: CORE_PEER_GOSSIP_ORGLEADER
          value: "false"
        - name: CORE_PEER_GOSSIP_USELEADERELECTION
          value: "true"
        - name: CORE_PEER_ID
          value: peer1.org2
        - name: CORE_PEER_LISTENADDRESS
          value: 0.0.0.0:7051
        - name: CORE_PEER_LOCALMSPID
          value: Org2MSP
        - name: CORE_PEER_PROFILE_ENABLED
          value: "true"
        - name: CORE_PEER_TLS_CERT_FILE
          value: /etc/hyperledger/fabric/tls/server.crt
        - name: CORE_PEER_TLS_ENABLED
          value: "true"
        - name: CORE_PEER_TLS_KEY_FILE
          value: /etc/hyperledger/fabric/tls/server.key
        - name: CORE_PEER_TLS_ROOTCERT_FILE
          value: /etc/hyperledger/fabric/tls/ca.crt
        - name: CORE_VM_ENDPOINT
          value: unix:///host/var/run/docker.sock
        - name: FABRIC_LOGGING_SPEC
          value: INFO
        
        resources: {}
        volumeMounts:
        - mountPath: /host/var/run/
          name: peer1-org2-claim0
        - mountPath: /etc/hyperledger/fabric/msp
          name: peer1-org2-claim1
        - mountPath: /etc/hyperledger/fabric/tls
          name: peer1-org2-claim2
        - mountPath: /var/hyperledger/production
          name: peer1-org2
        workingDir: /opt/gopath/src/github.com/hyperledger/fabric/peer
      restartPolicy: Always
      volumes:
      - name: peer1-org2-claim0
        hostPath:
          path: /var/run/ 
          type: Directory
      - name: peer1-org2-claim1
        hostPath:
          path: /home/admin1/k8s/test/HF-On-K8S/SingleNodeSetup/crypto-config/peerOrganizations/org2/peers/peer1.org2/msp 
          type: Directory
      - name: peer1-org2-claim2
        hostPath:
          path: /home/admin1/k8s/test/HF-On-K8S/SingleNodeSetup/crypto-config/peerOrganizations/org2/peers/peer1.org2/tls 
          type: Directory
      - name: peer1-org2
        hostPath:
          path: /home/admin1/k8s/test/HF-On-K8S/SingleNodeSetup/volumes/peer1.org2 
          type: Directory
status: {}


---
apiVersion: v1
kind: Service
metadata:
   namespace: org2
   name: peer1
spec:
 selector:
   app: hyperledger
   role: peer
   peer-id: peer1
   org: org2
 type: NodePort
 ports:
   - name: externale-listen-endpoint
     protocol: TCP
     port: 7051
     targetPort: 7051
   - name: chaincode-listen
     protocol: TCP
     port: 7052
     targetPort: 7052
   - name: peer-statedb-couchdb
     protocol: TCP
     port: 5984
     targetPort: 5984
