apiVersion: v1
kind: Namespace
metadata:
    name: org1

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: org1-pv
  labels:
    org: org1
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /opt/share/crypto-config/peerOrganizations/org1
    server: 10.88.68.51  #change to your nfs server ip here

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 namespace: org1
 name: org1-pv
spec:
 accessModes:
   - ReadWriteMany
 resources:
   requests:
     storage: 10Mi
 selector:
   matchLabels:
     org: org1   

---